### ISSUE TITLE
Minor repo settings improvements

### ISSUE THREAD

**Issue by terorie** [solana-foundation/specs#14]
Proposing the following repo changes

- Change the GitHub repo description to (in settings, shown in Twitter embeds). 
  - > Protocol specifications of the Solana network, maintained by various protocol teams.
  - Rationale: Makes language slightly more precise and underlines the fact that Solana Foundation only hosts the effort, but tries to remain netural.

- Disable merge and squash merges, only allow rebase merging.
  - Rationale: The spec repo can evolve arbitrarily at different places so we should disable merge commits for simplicity. Squash merging is annoying because it forces fusing commits together, even when this is unwanted sometimes. Rebase merging remains as the strategy closest to "committing to main, but with reviews".

**Comment by ripatel-jump** [comment]
@danpaul000 would you mind adjusting these?

**Comment by danpaul000** [comment]
Done and done.
