### ISSUE TITLE
Tracking: Solana Bytecode Format

### ISSUE THREAD

**Issue by riptl** [solana-foundation/specs#6]
SBF is live on mainnet but is missing a spec.

Current architectures:

- [ ] bpfel-solana (legacy)
- [ ] sbf
- [ ] sbfv2 (WIP)

**Proposed Content**

- Instruction Encoding
- Instruction Set
- Interpereter pseudocode
- CU metering

**Organization**

- *Section:* Runtime
- *Status*: Standard, live on mainnet

**Comment by terorie** [comment]
Useful resources:
- bpf.wtf writeup: https://bpf.wtf/sol-0x03-isa/
- Rust instruction set https://github.com/solana-labs/rbpf/blob/main/src/ebpf.rs
- Rust disassembler https://github.com/solana-labs/rbpf/blob/main/src/disassembler.rs
- Rust interpreter https://github.com/solana-labs/rbpf/blob/main/src/interpreter.rs
- Rust JIT compiler https://github.com/solana-labs/rbpf/blob/main/src/jit.rs
- LLVM BPF target https://github.com/solana-labs/llvm-project/tree/solana-rustc/14.0-2022-03-22/llvm/lib/Target/BPF
- Capstone BPF disassembler https://github.com/capstone-engine/capstone/tree/next/arch/BPF
- Binary Ninja plugin (Python) https://github.com/otter-sec/bn-ebpf-solana
- Binary Ninja plugin (C++) https://github.com/terorie/binaryninja-ebpf
- Go disassembler and interpreter https://pkg.go.dev/go.firedancer.io/radiance/pkg/sbf#pkg-constants
- Linux eBPF ISA v1.0 https://docs.kernel.org/bpf/instruction-set.html
- iovisor/bpf-spec https://github.com/iovisor/bpf-docs/blob/master/eBPF.md
