### ISSUE TITLE
Tracking: Ed25519

### ISSUE THREAD

**Issue by riptl** [solana-foundation/specs#8]
While Ed25519 is technically a standard, in reality the malleability check rules on signature verification are ambiguous.

Solana mainnet uses the ed25519-dalek `verify_strict` implementation.

**Proposed Content**

- Link to [RFC 8032 Section 5.1](https://www.rfc-editor.org/rfc/rfc8032#section-5.1)
- Exhaustive test fixtures 

**Organization**

- *Section:* Core
- *Status*: Standard, live on mainnet

**Comment by terorie** [comment]
Good resource: https://hdevalence.ca/blog/2020-10-04-its-25519am

**Comment by harsh4786** [comment]
Currently working on it
